ONE_SMALL_STEP/ONE_SMALL_STEP/ViewModels/PersonViewModel.cs
using ONE_SMALL_STEP.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AutoMapper;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ONE_SMALL_STEP.ViewModels
{
    public class PersonViewModel
    {
        //public List<PersonType> personTypeList { get; set; }
        //public List<Person> personlist { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int PersonID { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Email")]
        public string EmailAddress { get; set; }
        public string Screenshot { get; set; }
        //public Person person { get; set; }
        [Display(Name = "Contact Type")]
        //public PersonType PersonTypeName { get; set; }
        public string PersonType { get; set; }

        //public int PersonTypeID { get; set; }
        //public PersonType PersonType { get; set; }
        //public ICollection<PersonMessage> PersonMessage { get; set; }


    }
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ONE_SMALL_STEP.Core;
using ONE_SMALL_STEP.Core.Domain;
using ONE_SMALL_STEP.Models;
using ONE_SMALL_STEP.ViewModels;

namespace ONE_SMALL_STEP.Controllers
{
    public class PersonController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly OneSmallStepContext _context;

        public PersonController(IUnitOfWork unitOfWork, OneSmallStepContext context)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }
        

        //IEnumerable<TEntity> GetAll();
        //GET: Person
        //[AutoMap()]
        //public ActionResult Index()
        //{


        //    var domainModel = _unitOfWork.Person.Get(null, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType");
        //    var vm = Mapper.Map<IEnumerable<Person>, IEnumerable<PersonViewModel>>(domainModel);
        //    //return View(vm);

           
        //    //return View("~/Views/Person/Index.cshtml");
        //    return View("Person2");
        //}


        public ActionResult Index()
        {


            //var domainModel = _unitOfWork.Person.Get(null, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType");
            //var vm = Mapper.Map<IEnumerable<Person>, IEnumerable<PersonViewModel>>(domainModel);
            ////return View(vm);


            return View();
            //return View("IndexPerson");
        }



        public ActionResult Create()
        {
            var personTypes = _context.PersonType.ToList();
            CreatePersonViewModel model = new CreatePersonViewModel();
            model.PersonTypes = personTypes;

            return View(model);
            
        }

        // POST: Person/Create
        [HttpPost]
        public ActionResult Create(Person Person)
        {
            try
            {
                //Person person = new Person();
                //person.PersonID = createPersonView.PersonID;
                //person.Screenshot = createPersonView.Screenshot;
                //person.EmailAddress = createPersonView.EmailAddress;
                //person.FirstName = createPersonView.FirstName;
                //person.LastName = createPersonView.LastName;
                //person.PersonTypeID = createPersonView.PersonTypeID;
                //person.CreatedDate = DateTime.Now;

                _unitOfWork.Person.Add(Person);
                _unitOfWork.Complete();
                //using (var dbModel = new OneSmallStepContext())
                //{
                //    dbModel.Person.Add(person);
                //    dbModel.SaveChanges();
                //    //Console.WriteLine(person.emailAddress);
                //    //Console.ReadKey();

                //}
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch(DbEntityValidationException e)
            {

                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;

            }
        }
        // POST: Person/Edit/1
        [HttpGet]
        public ActionResult Edit(int id)
        {




            var entities = _unitOfWork.Person.SingleOrDefault(p => p.PersonID == id);
            //var entities = _unitOfWork.Person.GetByID(p => p.PersonID == id, includeProperties: "PersonType");

            //entities = Mapper.Map<IEnumerable<Person>, IEnumerable<EditPersonViewModel>>(entities);
            var PersonTypes = _context.PersonType.ToList();
            var vm = Mapper.Map<Person, EditPersonViewModel>(entities);
            vm.PersonTypes = PersonTypes;
            vm.PersonTypes.ToList();


            return View(vm);
        }

 

        [HttpPost]
        public ActionResult Edit(Person person)
        {
            _unitOfWork.Person.Add(person);
            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        [HttpGet]
        //[AutoMap(typeof(Person), typeof(DeletePersonViewModel))]
        public ActionResult Delete(int id)
        {                           
            var domainModel = _unitOfWork.Person.Get(p => p.PersonID == id, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType").FirstOrDefault();

            var vm = Mapper.Map<Person, DeletePersonViewModel>(domainModel);

  
            return View(vm);
        }



        [HttpPost]
        public ActionResult Delete (Person person)
        {

            var entities = _unitOfWork.Person.SingleOrDefault(p => p.PersonID == person.PersonID);

            _unitOfWork.Person.Remove(entities);
            //_unitOfWork.Person.Remove(person);
            
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }


    }
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Controllers/api/PersonController.cs
using AutoMapper;
using ONE_SMALL_STEP.Core;
using ONE_SMALL_STEP.Core.Domain;
using ONE_SMALL_STEP.Persistence.Repositories;
using ONE_SMALL_STEP.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ONE_SMALL_STEP.Controllers.api
{
    [RoutePrefix("api")]
    public class PersonController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly OneSmallStepContext _context;

        //public PersonController()
        //{     
        //}

        //public PersonController(IUnitOfWork unitOfWork)
        //{
        //    _unitOfWork = unitOfWork;
        //}

        public PersonController(IUnitOfWork unitOfWork, OneSmallStepContext context)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }



        //public IEnumerable<PersonViewModel> GetPerson()
        //public IEnumerable<PersonViewModel> GetPerson()
        //{
        //    //return _unitOfWork.Person.GetAll();
        //    //return _unitOfWork.Person.GetAll().Select(Mapper.CreateMap<Person, PersonViewModel>());
        //}
        //private IPersonRepository _repository;
        //public PersonContoller(IPersonRepository repository)
        //{
        //    _repository = repository;
        //}

        //public PersonViewModel Get()
        //{
        //    return _unitOfWork.Person;
        //}


        //public IEnumerable<PersonViewModel> GetPerson()
        //{
        //    //return _repository.PersonViewModel();
        //}
        //// GET api/<controller>
        //public IEnumerable<PersonViewModel> GetPerson()
        //{
        //    //return new string[] { "value1", "value2" };
        //    //var person = _unitOfWork.Person.GetAll();

        //    var person = _unitOfWork.
        //    //return _unitOfWork


        //    //return View(courses);

        //}
        //[HttpGet]
        [HttpGet]
        [Route("person")]
        public IEnumerable<PersonViewModel> Get()

        {
            //return _repository.GetProfileForEdit(User.Identity.Name);
            var domainModel = _unitOfWork.Person.Get(null, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType");

            //return _unitOfWork.Person.Get(null, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType");

            //return View(courses.ToList());

            var vm = Mapper.Map<IEnumerable<Person>, IEnumerable<PersonViewModel>>(domainModel);
            //var vm = Ok(Mapper.Map<IEnumerable<PersonViewModel>>(domainModel));
            //return (PersonViewModel)vm;
            
            return vm;

        }



        //public ActionResult Create()
        //{
        //    var personTypes = _context.PersonType.ToList();
        //    CreatePersonViewModel model = new CreatePersonViewModel();
        //    model.PersonTypes = personTypes;

        //    return View(model);

        //}


        // POST: api/EmployeesAPI
        //[ResponseType(typeof(Employee))]
        [HttpPost]
        [Route("person/create")]
        public IHttpActionResult PostPerson(Person Person)
            //public IHttpActionResult PostPerson(CreatePersonViewModel Person) >> need to switch to this<<<
        //public PersonViewModel PostPerson(Person Person)
        {
            //if (!ModelState.IsValid)
            //{
            //    return BadRequest(ModelState);
            //}

            //db.Employees.Add(employee);
            //db.SaveChanges();

            _unitOfWork.Person.Add(Person);
            _unitOfWork.Complete();

            //return Ok(Person);
            return Ok(Person.PersonID);

            //return CreatedAtRoute("DefaultApi", new {id = Person.PersonID }, Person);
            //return Request.CreateResponse(HttpStatusCode.OK, 1);
            //if (result > 0)
            //{
            //    return Request.CreateResponse(HttpStatusCode.Created, "Submitted Successfully");
            //}
            //else
            //{
            //    return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Something wrong !");
            //}
            //return CreatedAtRoute("DefaultApi", new { id = employee.EmpNo }, employee);
        }


        // POST api/Person  
        public HttpResponseMessage Post(Person Person)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Person.Add(Person);
                _unitOfWork.Complete();
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, Person);
                return response;
            }
            else
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
        }




        // POST: Person/Edit/1
        [HttpGet]
        [Route("person/{personId}")]
        public EditPersonViewModel Get(int personId)
        {

            var entities = _unitOfWork.Person.SingleOrDefault(p => p.PersonID == personId);
            //var entities = _unitOfWork.Person.GetByID(p => p.PersonID == id, includeProperties: "PersonType");

            //entities = Mapper.Map<IEnumerable<Person>, IEnumerable<EditPersonViewModel>>(entities);
            //var PersonTypes = _context.PersonType.ToList();
            var vm = Mapper.Map<Person, EditPersonViewModel>(entities);
            //vm.PersonTypes = PersonTypes;
            //vm.PersonTypes.ToList();


            return (vm);
        }

        //public IHttpActionResult GetPersonTypes()
        //{
        //    var personType = new PersonType();


        //}

        //[Route("person/update/{personId}")]
        [HttpPut]
        [Route("person/update")]
        //api/person/delete/" + personId,
        //public PersonViewModel Update(int personId, Person Person)
        public PersonViewModel Update(Person Person)
        {
            //var domainModel = _unitOfWork.Person.Get(x => x.PersonID == personId).FirstOrDefault();

            //_unitOfWork.Person.Update(domainModel);
            _unitOfWork.Person.Update(Person);
            _unitOfWork.Complete();
            //var vm = Mapper.Map<Person, PersonViewModel>(domainModel);
            var vm = Mapper.Map<Person, PersonViewModel>(Person);
            return vm;
        }

        [Route("person/delete/{personId}")]
        //api/person/delete/" + personId,
        public PersonViewModel Delete(int personId)
        {
            var domainModel = _unitOfWork.Person.Get(x => x.PersonID == personId).FirstOrDefault();
            
            _unitOfWork.Person.Remove(domainModel);
            _unitOfWork.Complete();
            var vm = Mapper.Map<Person,PersonViewModel>(domainModel);
            return vm;
        }
        [Route("person/personType")]
        public IEnumerable<PersonTypeViewModel> GetPersonTypes()

        {
            //return _repository.GetProfileForEdit(User.Identity.Name);
            //var domainModel = _unitOfWork.PersonType.Get(null, x => x.OrderBy(z => z.PersonTypeName), includeProperties: "PersonType");
            var domainModel = _unitOfWork.PersonType.Get(null, x => x.OrderBy(z => z.PersonTypeName));

            //return _unitOfWork.Person.Get(null, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType");

            var vm = Mapper.Map<IEnumerable<PersonType>, IEnumerable<PersonTypeViewModel>>(domainModel);

            //var vm = Mapper.Map<IEnumerable<PersonType>, IEnumerable<PersonTypeViewModel>>(domainModel);
            //var vm = Ok(Mapper.Map<IEnumerable<PersonTypeViewModel>>(domainModel));
            //return (PersonViewModel)vm;
            //return vm;
            //var personType = _context.PersonType.ToList();
            return vm;

        }


        ////[HttpGet]
        //////[AutoMap(typeof(Person), typeof(DeletePersonViewModel))]
        ////public ActionResult Delete(int id)
        //[Route("person/delete/{personId}")]
        //public IEnumerable<DeletePersonViewModel> Delete(int personId)
        //{
        //    var domainModel = _unitOfWork.Person.Get(p => p.PersonID == personId, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType").FirstOrDefault();

        //    var vm = Mapper.Map<Person, DeletePersonViewModel>(domainModel);


        //    return vm;
        //}



        //// GET api/<controller>/5
        //public string Get(int id)
        //{
        //    var domainModel = _unitOfWork.Person.Get(x => x.PersonID == id, x => x.OrderBy(z => z.LastName), includeProperties: "PersonType").SingleOrDefault();
        //    //return View(courses.ToList());

        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }
        //    //return Ok(Mapper.Map<IEnumerable<Person>, IEnumerable<PersonViewModel>>(domainModel));
        //    return Ok(Mapper.Map<Person, PersonViewModel>(domainModel));

        //    //return "value";
    }

        //// POST api/<controller>
        //public void Post([FromBody]string value)
        //{
        //}

        //// PUT api/<controller>/5
        //public void Put(int id, [FromBody]string value)
        //{
        //}

        //// DELETE api/<controller>/5
        //public void Delete(int id)
        //{
        //}
    }

ONE_SMALL_STEP/ONE_SMALL_STEP/Controllers/person_oldController.cs
using ONE_SMALL_STEP.Core.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ONE_SMALL_STEP.Controllers
{
    public class person_oldController : Controller
    {
        OneSmallStepContext db = new OneSmallStepContext();
        // GET: person_old
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            ViewBag.PersonTypeID = new SelectList(db.PersonType, "PersonTypeID", "PersonTypeName");
            return View();
        }
    }
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/AddNewPerson.cshtml
@model ONE_SMALL_STEP.Data.Person

@{
    ViewBag.Title = "AddNewPerson";
}

<h2>AddNewPerson</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Screenshot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Screenshot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Screenshot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonTypeID, "PersonTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestName1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestName1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestName1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestName2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestName2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestName2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestName3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestName3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestName3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/Create_ORIG.cshtml
@model  ONE_SMALL_STEP.ViewModels.CreatePersonViewModel
@{
    ViewBag.Title = "Create New Contact";
}

<h2>Create</h2>

@*<p>
        @Html.ActionLink("Create New Person", "Create")
    </p>*@

@using (Html.BeginForm("Create", "Person", FormMethod.Post))
{
    @*<table class="table-striped">
        <tr>
            <th>@Html.DisplayNameFor(m => m.Person)</th>
            <th>@Html.DisplayNameFor(m => m.PersonTypes)</th>

        </tr>
        <tr>
            <td></td>
        </tr>*@
    @*</table>*@

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmailAddress)
        @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Screenshot)
        @Html.TextBoxFor(m => m.Screenshot, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PersonTypes)
        @*@Html.DropDownListFor(m => m.PersonTypes,)*@
        @Html.DropDownListFor(m => m.PersonTypeID, new SelectList(Model.PersonTypes, "PersonTypeID", "PersonTypeName"), "", new { @class = "form-control" })
        @*@Html.DropDownListFor(m => m.PersonTypeID, new SelectList(Model.PersonTypes, "PersonTypeID", "PersonTypeName"), "", new { @class = "form-control" })*@
    </div>
    @Html.HiddenFor(m => m.PersonID)
    <button type="submit" class="btn-primary">Save</button>
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/Edit.cshtml
@model  ONE_SMALL_STEP.ViewModels.EditPersonViewModel
@{
    ViewBag.Title = "Edit Contact";
}

<h2>Edit</h2>

@*<p>
        @Html.ActionLink("Create New Person", "Create")
    </p>*@

@using (Html.BeginForm("Edit", "Person", FormMethod.Post))
{
    @*<table class="table-striped">
        <tr>
            <th>@Html.DisplayNameFor(m => m.Person)</th>
            <th>@Html.DisplayNameFor(m => m.PersonTypes)</th>

        </tr>
        <tr>
            <td></td>
        </tr>*@
    @*</table>*@

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmailAddress)
        @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Screenshot)
        @Html.TextBoxFor(m => m.Screenshot, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PersonTypes)
        @*@Html.DropDownListFor(m => m.PersonTypes,)*@
        @Html.DropDownListFor(m => m.PersonTypeID, new SelectList(Model.PersonTypes, "PersonTypeID", "PersonTypeName", Model.PersonTypeID), "", new { @class = "form-control" })
        @*@Html.DropDownListFor(m => m.PersonTypeID, new SelectList(Model.PersonTypes, "PersonTypeID", "PersonTypeName"), "", new { @class = "form-control" })*@
    </div>
    @Html.HiddenFor(m => m.PersonID)
    <button type="submit" class="btn-primary">Save</button>
}

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/IndexMVC.cshtml
@model IEnumerable<ONE_SMALL_STEP.ViewModels.PersonViewModel>

@{
    ViewBag.Title = "Contacts";
}

<h2>Index2</h2>

<p>
    @Html.ActionLink("Create New Contact", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Screenshot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PersonTypeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Screenshot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PersonTypeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.PersonID}) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.PersonID})
        </td>
    </tr>
}

</table>

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/Index_ORIG.cshtml
@model IEnumerable<ONE_SMALL_STEP.ViewModels.PersonViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create new Person", "Create", "person_old")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PersonTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Screenshot)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.PersonType_personTypeId)
            </th>*@
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonTypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Screenshot)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.PersonTypeId)
                </td>*@
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item. }) |
                    @Html.ActionLink("Details", "Details", new { id=item.PersonID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.PersonID })
                </td>*@
        </tr>
    }

</table>

ONE_SMALL_STEP/ONE_SMALL_STEP/Views/Person/indextest.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}